### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by iDoka** [Const-me/Whisper#1]
Thanks for your great job!
Any chances to see porting on linux in roadmap?

**Comment by Const-me** [comment]
@iDoka Not unless someone pays me to do that. I think that’s going to be rather hard to accomplish.

Ideally, need to rewrite pretty much everything: Vulkan instead of D3D11, GLSL instead of HLSL, and FFmpeg (or maybe GStreamer) instead of Media Foundation.

Could consider [Diligent Engine](http://diligentgraphics.com/diligent-engine/) for GPU abstraction, at least the compute shaders will stay in HLSL. I have used it in the past on Linux, on top of GLES 3.1. It worked amazingly well for my use case, but for that project I didn’t need any compute shaders, I only needed 3D graphics. And even with Diligent Engine, porting is still a lot of work.

If you want that software on Linux, I suggest Wine. I don’t have hands-on experience, but I heard good things about [DXVK 2.0.](https://github.com/doitsujin/dxvk) Apparently, that thing’s good enough to run D3D11 Windows games on Linux-based SteamOS. Many triple-A D3D11 games are using tons of compute shaders, if DXVK runs these games, it will probably work fine with the compute shaders in this library.
