### ISSUE TITLE
Crashing and resetting my computer when trying to transcribe

### ISSUE THREAD

**Issue by jogianni** [Const-me/Whisper#108]
I am trying to transcribe a .m4a file using the gpu AMD Radeon RX 6950 XT. I select file, output, and text and it immediately resets my computer. 

Using windows 10, updated the amd drivers and pytorch

have an i7 6700k cpu

**Comment by Highlander1536** [comment]
Just a random thought, but is your system overclocked or anything like that? Cause this app shouldnt cause the computer to reset like that. It sounds like a hardware thing

**Comment by jogianni** [comment]
I e just installed the hardware so I really doubt it. Is there a way I
could reset it to basic settings just in case?

**Comment by Highlander1536** [comment]
If you touched anything on your bios settings you could probably just go to system defaults pretty easily. But all Motherboards are different so it might take a bit of looking around.

**Comment by Const-me** [comment]
@jogianni On paper, your PC is awesome for this software. It’s some weird thing with your particular computer.

To verify the hypothesis run some GPU benchmark, like free trial [of that software](https://www.passmark.com/products/performancetest/pt_advdirectcompute.php).
If some of these DirectCompute tests will also reset your computer, you’ll confirm the issue is unrelated to my software.

In that case, my first suspect would be power supply. [Wikipedia says](https://en.wikipedia.org/wiki/Radeon_RX_6000_series#Desktop) your GPU designed to consume 335 W, however a [picture on that page](https://www.techpowerup.com/review/amd-radeon-rx-6950-xt-reference-design/35.html) says the card they tested peaked at 450W. And they have tested a card with reference design: if you have a different one, it might peak at even more watts.

Your CPU peaks at 100W. If your PSU is rated less than 650W, sudden computer reset is expected when under load.

**Comment by emcodem** [comment]
Only time i have seen immediate resets was when psu was not strong enough for 100% concurrent utilisation of builtin gpu.

**Comment by Const-me** [comment]
@jogianni That list says you have two GPUs in that computer, nVidia 1070 and AMD 6950 XT ?

If so, the 750W PSU is probably the issue, and you can test without buying extra hardware.

Shut down the computer, unplug the power cord, open the case.
Remove the nVidia GPU form the computer so you only left with a single AMD Radeon GPU.
If your AMD GPU is not in the slot PCIE2 (the slot which is closer to the processor), move the Radeon into that slot.

Then try to reproduce the issue.
