### ISSUE TITLE
Opened the Debug Console cmd window output Chinese garbled how to do?

### ISSUE THREAD

**Issue by fgr178707** [Const-me/Whisper#152]
Opened the Debug Console cmd window output Chinese garbled how to do?

The model used is ggml-large

The cmd window uses chcp 65001=UTF-8

![QQ截图20230801172744](https://github.com/Const-me/Whisper/assets/109357981/f3f3b590-b904-4780-b71f-cb52e1511d7d)

**Comment by emcodem** [comment]
Can you try the windows feature: "Beta: use unicode UTF-8 for world wide language support" feature?
It's a checkbox in Region->administrative->Change System Locale
https://www.youtube.com/watch?v=Ahu6rcMYDHk

The guy in the youtube video plays with language settings but i mean this checkbox you see there....

**Comment by fgr178707** [comment]
> Can you try the windows feature: "Beta: use unicode UTF-8 for world wide language support" feature? It's a checkbox in Region->administrative->Change System Locale https://www.youtube.com/watch?v=Ahu6rcMYDHk
> 
> The guy in the youtube video plays with language settings but i mean this checkbox you see there....

Tried enabling "Beta: use unicode UTF-8 for global language support".
Still doesn't help
Turning it on and off makes no difference, it's still garbled.

**Comment by emcodem** [comment]
OK sorry for the shot in the dark. 
I have a hard time reproducing the issue because of missing example audio that produces unsupported characters. 
Do you also see the same issue with special chars in the filename? I tried "にっぽん.wav", which i believe are japanese characters and each character takes 3-bytes but i see the filename of the wav correctly printed in the debug window. Added some chinese chars but it's the same: にっぽん_我的氣墊船充滿了鱔魚_東京.wav

Might you share a small audio sequence that contains the problematic area?

**Comment by fgr178707** [comment]
> OK sorry for the shot in the dark. I have a hard time reproducing the issue because of missing example audio that produces unsupported characters. Do you also see the same issue with special chars in the filename? I tried "にっぽん.wav", which i believe are japanese characters and each character takes 3-bytes but i see the filename of the wav correctly printed in the debug window. Added some chinese chars but it's the same: にっぽん_我的氣墊船充滿了鱔魚_東京.wav
> 
> Might you share a small audio sequence that contains the problematic area?

Only the cmd window displays garbled code
There is no problem with the output file

**Comment by emcodem** [comment]
Yeah i thought so. A very short file for testing would still have made my life easier.
Can you please test if this works as expected for you?

[WhisperDesktop_nocolors.zip](https://github.com/Const-me/Whisper/files/12290047/WhisperDesktop_nocolors.zip)

I disabled colorizing token probability in logger.cpp, function logNewSegments

**Comment by fgr178707** [comment]
> Yeah i thought so. A very short file for testing would still have made my life easier. Can you please test if this works as expected for you?
> 
> [WhisperDesktop_nocolors.zip](https://github.com/Const-me/Whisper/files/12290047/WhisperDesktop_nocolors.zip)
> 
> I disabled colorizing token probability in logger.cpp, function logNewSegments

I tried this version and it's better
It's all in Chinese.

**Comment by emcodem** [comment]
Thanks @fgr178707  you could have left the case open because you found kind of a bug.

@Const-me 
OK so the ANSI colorizing k_colors in logger.cpp somehow disturbs the makeUtf16 convert function. Sorry but i did not find a way yet how to actually support both, "printing colors and full utf8 console logging" support. Disabling the colors works in this case but the Desktop Version does not provide an option for disable colors.

**Comment by emcodem** [comment]
Oh, i have overseen this PR:
https://github.com/Const-me/Whisper/pull/122/commits/55702897350232ba69031c7773f3c56196f1b32a
somehow my guts say that this strategy could work here too...

**Comment by emcodem** [comment]
Also mention the first time this problem was raised (in a very professional way):
https://github.com/Const-me/Whisper/issues/37
