### ISSUE TITLE
When will there be a Mac desktop program?

### ISSUE THREAD

**Issue by everfu** [Const-me/Whisper#173]
When will there be a Mac desktop program?

**Comment by RickArcher108** [comment]
There is: https://getwavery.com/

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***


From: Jose wan ***@***.***>
Sent: Thursday, September 14, 2023 1:00 AM
To: Const-me/Whisper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Const-me/Whisper] When will there be a Mac desktop program? (Issue #173)


When will there be a Mac desktop program?

**Comment by tjesp** [comment]
There is MacWhisper. From the Youtube videos I have seen it looks great!

**Comment by Makememo** [comment]
Maybe try [http://memo.ac](http://memo.ac) , support for Windows MAC dual platform, there are beautiful GUI, translation and other functions.

**Comment by emcodem** [comment]
Note that there is no connection between the so far mentioned tools and Const-Me Whisper GPU technology from this repository.

A humble try of explaination:
The technology introduced in this repository is bound to windows, it might be used on Linux/MacOS using "wine" but that can be considered kind of special interest usage. After all, this project is bound to windows because of the use of windows native API's like DirectX.  @Const-me might have a much better explaination tough.

**Comment by everfu** [comment]
> Note that there is no connection between the so far mentioned tools and Const-Me Whisper GPU technology from this repository.
> 
> A humble try of explaination:
> The technology introduced in this repository is bound to windows, it might be used on Linux/MacOS using "wine" but that can be considered kind of special interest usage. After all, this project is bound to windows because of the use of windows native API's like DirectX.  @Const-me might have a much better explaination tough.

sure
