### ISSUE TITLE
App crash on model loading

### ISSUE THREAD

**Issue by hakkai2015** [Const-me/Whisper#31]
I try to load model and app crash without any message. I tried with different models (tiny, small, medium, large) with no result. I use Win10x64. GPU - GTX 970 4 Gb, CPU - i7 3930K, RAM - 28 Gb. Also I tested app on VM with the same result.

**Comment by Const-me** [comment]
@hakkai2015 I have tested on a different nVidia GPU with 4GB VRAM, GeForce GTX 1650. On paper, your GPU is faster. That computer also runs Windows 10.

How specifically have you got 28 GB RAM? If you have 3 memory modules installed 4GB, 8GB and 16GB it should be fine, but if you’re using some kind of virtualization like VMware ESXi that might cause issues.

Here’s some steps to troubleshoot.

1. Run dxdiag.exe, look at the “Display” tab. The important values you should see there are Direct3D Acceleration: Enabled, and Notes: No problems found
If you see something else, it could be something wrong with your GPU driver or hardware.

3. Open Windows Explorer, paste the following string to address bar `%LOCALAPPDATA%\CrashDumps` press enter, and look for the `*.dmp` files in that folder with the name starting with `WhisperDesktop` If you find some, ZIP one of these files, upload somewhere, and link in the comment here, I will look.

**Comment by hakkai2015** [comment]
I have 7 x 4 GB RAM modules and use 7 of 8 slots in my Motherboard.

Dxdiag shows: Direct3D Acceleration is ON and No problems found. I don't use virtualization on my PC and ran VM just for test if app will work.

Link to crush dumps: https://disk.yandex.ru/d/t7ShKH_KOYm63g

**Comment by Const-me** [comment]
@hakkai2015 Thanks for the crash dumps. Your GPU should work fine, it crashes because your CPU is too old. The runtime exception in that dump says “Illegal instruction”, I’ve discovered the software requires [F16C](https://en.wikipedia.org/wiki/F16C) instruction set extension.

I’ve tried to emulate these instructions, but found it’s very hard to do correctly.
Neither [DirectXMath](https://learn.microsoft.com/en-us/windows/win32/api/directxpackedvector/nf-directxpackedvector-xmconvertfloattohalf) nor [FP16](https://github.com/Maratyszcza/FP16/) library are correct.

If you can program C++, create a private fork and fix yourself. I think the only place which uses these instructions is LookupTablesData constructor, [there](https://github.com/Const-me/Whisper/blob/1.8.0/Whisper/ML/LookupTablesData.cpp).
You can generate these two arrays on some other computer, then load that data instead of computing it on startup.

I don’t want to do that in master because these two lookup tables are using 256kb of memory combined, gonna inflate size of Whisper.dll by 60% if embedded there.

I’ve documented the requirement, and implemented proper error handling. Version 1.8 should show you the appropriate error message on startup, instead of the crash.
