### ISSUE TITLE
Adding speaker diarization as a feature

### ISSUE THREAD

**Issue by RYucel** [Const-me/Whisper#7]
Is it possible in future to add speaker diarization as an option to have labels for who speaks which part of the transcription? Very good project results btw. Thanks

**Comment by Const-me** [comment]
@RYucel  Try the new version 1.6.
While very simple (only couple pages of code which should be identical to the original version in whisper.cpp), I can’t say I’m happy with how it performs.
In my tests, it was only reliable when capturing live audio from my [Blue Yeti](https://www.bluemic.com/en-us/products/yeti/) microphone, and only after I’ve switched the microphone’s pattern to “Stereo”.
For pre-recorded audio however, it often outputs `Unsure` value, which means it was unable to detect the speaker because the left/right levels were too close.

**Comment by RYucel** [comment]
Thank you for your reply. Great results for now. Btw, if I would like to modify GUI (to my own language) which file(s) I should check? I could not find it

**Comment by Const-me** [comment]
@RYucel  For development time and readability, I neglected internationalization support in the software. The strings are all over the place. Here’s the main parts for the Win32 GUI sample.

1. Dialogs templates are in `Examples/WhisperDesktop/WhisperDesktop.rc` file. Double click in Visual Studio and you’ll see 5 dialog templates, the `IDD_ABOUTBOX` is unused, a remnant from the default project template. 

2. Many `*.cpp` files in WhisperDesktop project contain strings visible in message boxes. Most of them are in the dialog classes, the 3 main ones are `LoadModelDlg.cpp`, `TranscribeDlg.cpp`, `CaptureDlg.cpp`. Some of them are in other places, like `isInvalidTranslate` function in `Utils/miscUtils.cpp` source file.

3. Finally, when things fail with exceptions, message boxes contain messages printed by the code in `Whisper.dll`. The strings are scattered all over the place. See Whisper/Utils/Logger.h header, the `logError`, `logError16`, and `logErrorHr` functions are producing the messages. You can use “Find all references” IDE command to locate the callers.

P.S. The strings logged from Whisper.dll use UTF-8 encoding, as opposed to UTF-16 encoding in the desktop example. I wanted to save a bit of RAM, and I thought most people just write them into some log file and call it a day. Files on disks (also on the web) traditionally use UTF-8, as opposed to UTF-16.

**Comment by stevevaius2015** [comment]
Thank you very much
