### ISSUE TITLE
Not detecting multiple of same GPU cards as different cards

### ISSUE THREAD

**Issue by ClausMandal** [Const-me/Whisper#96]
I have two 2070 cards in one machine. I can only select one, no matter which of the GPUs I select in the dropdown, since they have same name. They should be numbered. Not a problem, but would be nice to select the card that isn't being used by the system. It looks like this when listed from CLI:

>main -la
Available graphic adapters:
"NVIDIA GeForce RTX 2070"
"NVIDIA GeForce RTX 2070"
"Microsoft Basic Render Driver"

Thanks for a very useful and super fast program!

**Comment by Const-me** [comment]
@ClausMandal The desktop app doesn’t support the feature. When two GPUs have the same name, will always use the first one. Will probably fix somehow when I have time.

If you’re using CLI or PowerShell, you can use 0-based index instead of the GPU name. Pass "0" to the GPU name parameter to use the first of your GPUs, or "1" to use the second one.
